//! Bazel `rules_jvm_external` lock files (`maven_install.json` -> OSV `Maven`).
//!
//! Only the lock file holds fully-resolved pinned coordinates;
//! `MODULE.bazel` / `WORKSPACE` carry author-declared ranges and are
//! intentionally not parsed. The OSV name is `groupId:artifactId`
//! (case-sensitive, classifier/packaging stripped); versions pass through
//! verbatim (Maven has its own comparator).
//!
//! Two schema generations, auto-detected by top-level key:
//! - NEW (>= 5.1, `"version": "2"`): `artifacts` map keyed by
//!   `groupId:artifactId[:packaging[:classifier]]` with `{ "version": .. }`.
//! - LEGACY (<= 5.0): `dependency_tree.dependencies` array of
//!   `{ "coord": "group:artifact[:packaging[:classifier]]:version" }`.
//!
//! The marker `__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY` ==
//! `THERE_IS_NO_DATA_ONLY_ZUUL` fingerprints these files so unrelated JSON is
//! never hijacked.

use super::support::{Emitter, read_text};
use super::{ScanTarget, file_name, find_line};
use serde_json::Value as JsonValue;
use std::path::Path;

/// One pinned Maven coordinate (OSV `groupId:artifactId` + resolved version).
struct MavenCoord {
    name: String,
    version: String,
}

pub struct BazelMavenTarget;

impl ScanTarget for BazelMavenTarget {
    fn ecosystem_id(&self) -> &'static str {
        "maven"
    }

    fn detects(&self, path: &Path) -> bool {
        // The lock file is user-nameable but generated names all end in
        // `install.json`; content fingerprinting in `parse` keeps unrelated
        // `*install.json` files from being misattributed.
        matches!(file_name(path), Some(name) if name.ends_with("install.json"))
    }

    fn parse(&self, path: &Path, out: &mut Emitter<'_>) {
        let Some(contents) = read_text(path, out) else {
            return;
        };
        // Malformed JSON (e.g. an interrupted repin) warns instead of
        // aborting the scan.
        let Ok(coords) = parse_lock(&contents) else {
            out.warn("rules_jvm_external lock file is not valid JSON");
            return;
        };
        for c in coords {
            out.pkg(&c.name, &c.version, find_line(&contents, &c.name));
        }
    }
}

/// Anchors on the `ZUUL` fingerprint or the structural top-level keys so an
/// unrelated `*install.json` is never grabbed.
fn is_rules_jvm_external(root: &JsonValue) -> bool {
    let Some(obj) = root.as_object() else {
        return false;
    };
    if obj
        .get("__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY")
        .and_then(|v| v.as_str())
        == Some("THERE_IS_NO_DATA_ONLY_ZUUL")
    {
        return true;
    }
    obj.contains_key("dependency_tree") || obj.get("artifacts").is_some_and(|v| v.is_object())
}

/// Reduce a coordinate key to the OSV name `groupId:artifactId`: keep the
/// first two `:`-segments, drop packaging/classifier. Case is preserved:
/// artifactIds can carry uppercase (`biz.aQute.bnd:...`) and OSV keys are
/// case-sensitive.
fn osv_name(coord_key: &str) -> Option<String> {
    let mut parts = coord_key.splitn(3, ':');
    let group = parts.next()?;
    let artifact = parts.next()?;
    if group.is_empty() || artifact.is_empty() {
        return None;
    }
    Some(format!("{group}:{artifact}"))
}

/// Extract pinned Maven coordinates from a lock-file body. Classifier
/// variants de-duplicate to one `(name, version)`; schema-version fields
/// (top-level `"version": "2"`, `dependency_tree.version`) are never emitted
/// as package data.
fn parse_lock(contents: &str) -> Result<Vec<MavenCoord>, serde_json::Error> {
    let root: JsonValue = serde_json::from_str(contents)?;
    if !is_rules_jvm_external(&root) {
        return Ok(Vec::new());
    }

    let mut out: Vec<MavenCoord> = Vec::new();
    let mut push = |name: String, version: String| {
        if version.is_empty() {
            return;
        }
        if out.iter().any(|c| c.name == name && c.version == version) {
            return; // collapse classifier/duplicate variants
        }
        out.push(MavenCoord { name, version });
    };

    if let Some(tree) = root.get("dependency_tree") {
        if let Some(deps) = tree.get("dependencies").and_then(|v| v.as_array()) {
            for dep in deps {
                let Some(coord) = dep.get("coord").and_then(|v| v.as_str()) else {
                    continue;
                };
                // Version is always the LAST segment; a 2-segment coord has
                // no version and is skipped.
                let segments: Vec<&str> = coord.split(':').collect();
                if segments.len() < 3 {
                    continue;
                }
                let Some(name) = osv_name(coord) else {
                    continue;
                };
                let Some(version) = segments.last() else {
                    continue;
                };
                push(name, (*version).to_string());
            }
        }
    } else if let Some(artifacts) = root.get("artifacts").and_then(|v| v.as_object()) {
        for (key, val) in artifacts {
            let Some(name) = osv_name(key) else {
                continue;
            };
            let Some(version) = val.get("version").and_then(|v| v.as_str()) else {
                continue;
            };
            push(name, version.to_string());
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    const NEW_FORMAT: &str = r#"{
      "__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY": "THERE_IS_NO_DATA_ONLY_ZUUL",
      "artifacts": {
        "com.google.code.gson:gson": { "shasums": { "jar": "abc" }, "version": "2.11.0" },
        "com.google.guava:guava": { "shasums": { "jar": "def" }, "version": "33.2.1-jre" },
        "biz.aQute.bnd:biz.aQute.bnd.util": { "shasums": { "jar": "ghi" }, "version": "6.4.0" },
        "com.google.guava:guava:jar:sources": { "shasums": { "jar": "jkl" }, "version": "33.2.1-jre" }
      },
      "dependencies": { "com.google.guava:guava": ["com.google.code.gson:gson"] },
      "version": "2"
    }"#;

    const LEGACY_FORMAT: &str = r#"{
      "dependency_tree": {
        "version": "0.1.0",
        "dependencies": [
          { "coord": "com.google.code.gson:gson:2.8.6", "sha256": "x" },
          { "coord": "com.google.guava:guava:jar:sources:30.0-jre", "sha256": "y" },
          { "coord": "org.example:nover", "sha256": "z" }
        ]
      }
    }"#;

    #[test]
    fn parses_new_format_and_strips_classifiers() {
        let coords = parse_lock(NEW_FORMAT).expect("valid json");
        let pairs: Vec<(&str, &str)> = coords
            .iter()
            .map(|c| (c.name.as_str(), c.version.as_str()))
            .collect();
        // Case preserved (biz.aQute.bnd); guava:jar:sources collapses to guava;
        // the schema `"version": "2"` is never emitted.
        assert!(pairs.contains(&("com.google.code.gson:gson", "2.11.0")));
        assert!(pairs.contains(&("com.google.guava:guava", "33.2.1-jre")));
        assert!(pairs.contains(&("biz.aQute.bnd:biz.aQute.bnd.util", "6.4.0")));
        assert_eq!(
            pairs
                .iter()
                .filter(|(n, _)| *n == "com.google.guava:guava")
                .count(),
            1
        );
        assert_eq!(coords.len(), 3);
    }

    #[test]
    fn parses_legacy_coord_strings() {
        let coords = parse_lock(LEGACY_FORMAT).expect("valid json");
        let pairs: Vec<(&str, &str)> = coords
            .iter()
            .map(|c| (c.name.as_str(), c.version.as_str()))
            .collect();
        // 3-seg -> group:artifact:version; 5-seg -> classifier dropped, last
        // segment is version; 2-seg (no version) -> skipped.
        assert!(pairs.contains(&("com.google.code.gson:gson", "2.8.6")));
        assert!(pairs.contains(&("com.google.guava:guava", "30.0-jre")));
        assert!(pairs.iter().all(|(n, _)| *n != "org.example:nover"));
        assert_eq!(coords.len(), 2);
    }

    #[test]
    fn ignores_unrelated_json_and_malformed_input() {
        // No rules_jvm_external fingerprint -> no coordinates.
        assert!(
            parse_lock(r#"{"name":"foo","version":"1.0.0"}"#)
                .expect("valid json")
                .is_empty()
        );
        // Malformed JSON surfaces as Err (`emit` turns it into a warning).
        assert!(parse_lock(r#"{ "artifacts": { "#).is_err());
    }
}
