//! Gleam (`manifest.toml` -> OSV `Hex`).
//!
//! Gleam publishes to Hex, so coordinates reuse the `"hex"` ecosystem id
//! (shared with Elixir's `mix.lock` and Erlang's rebar lock). The generated
//! lock file's top-level `packages` array holds fully-resolved pins:
//!
//! ```toml
//! packages = [
//!   { name = "gleam_stdlib", version = "0.63.2", source = "hex", ... },
//! ]
//! ```
//!
//! `manifest.toml` is a generic filename, so detection is gated on a sibling
//! `gleam.toml` (the unique Gleam project marker). Only `source = "hex"`
//! entries are valid Hex/OSV coordinates; `git`/`local` entries are skipped.

use super::support::{Emitter, LineFinder, read_text};
use super::{ScanTarget, file_name};
use std::path::Path;

pub struct GleamTarget;

impl ScanTarget for GleamTarget {
    fn ecosystem_id(&self) -> &'static str {
        "hex"
    }

    fn detects(&self, path: &Path) -> bool {
        // Lowercase only: Julia's capitalized `Manifest.toml` belongs to the
        // Julia target.
        if !matches!(file_name(path), Some("manifest.toml")) {
            return false;
        }
        path.parent()
            .map(|dir| dir.join("gleam.toml").is_file())
            .unwrap_or(false)
    }

    fn parse(&self, path: &Path, out: &mut Emitter<'_>) {
        if let Some(contents) = read_text(path, out) {
            parse_manifest(&contents, out);
        }
    }
}

/// Names and SemVer versions pass through unchanged. A corrupt/stale
/// manifest (a known real issue: gleam-lang/gleam #4173, #3891) degrades to
/// a warning rather than aborting the scan.
fn parse_manifest(contents: &str, out: &mut Emitter<'_>) {
    let Ok(toml) = toml::from_str::<toml::Value>(contents) else {
        out.warn("manifest.toml is not valid TOML");
        return;
    };
    let Some(packages) = toml.get("packages").and_then(|v| v.as_array()) else {
        return;
    };
    let mut lines = LineFinder::new(contents);
    for entry in packages {
        if entry.get("source").and_then(|v| v.as_str()) != Some("hex") {
            continue;
        }
        let (Some(name), Some(version)) = (
            entry.get("name").and_then(|v| v.as_str()),
            entry.get("version").and_then(|v| v.as_str()),
        ) else {
            continue;
        };
        if name.is_empty() || version.is_empty() {
            continue;
        }
        out.pkg(name, version, lines.find(name));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scan::targets::support::run_parser;

    const SAMPLE: &str = r#"
# This file was generated by Gleam
# You typically do not need to edit this file

packages = [
  { name = "gleam_stdlib", version = "0.63.2", build_tools = ["gleam"], requirements = [], otp_app = "gleam_stdlib", source = "hex", outer_checksum = "962B25" },
  { name = "gleam_erlang", version = "1.3.0", build_tools = ["gleam"], requirements = ["gleam_stdlib"], otp_app = "gleam_erlang", source = "hex", outer_checksum = "1124AD" },
  { name = "thoas", version = "1.2.1", build_tools = ["rebar3"], requirements = [], otp_app = "thoas", source = "hex", outer_checksum = "E38697" },
  { name = "my_local_lib", version = "1.0.0", build_tools = ["gleam"], source = "local", path = "../my_local_lib" },
  { name = "some_fork", version = "0.1.0", build_tools = ["gleam"], source = "git", repo = "https://example.com/x.git", commit = "abc" },
]

[requirements]
gleam_stdlib = { version = ">= 0.60.0 and < 2.0.0" }
"#;

    #[test]
    fn parses_only_hex_sourced_packages() {
        let pkgs = run_parser("hex", SAMPLE, parse_manifest);
        let names: Vec<&str> = pkgs.iter().map(|p| p.name.as_str()).collect();
        // Hex entries kept verbatim; `local` + `git` entries dropped.
        assert_eq!(names, ["gleam_stdlib", "gleam_erlang", "thoas"]);
        assert_eq!(pkgs[0].version, "0.63.2");
        assert_eq!(pkgs[1].version, "1.3.0");
    }

    #[test]
    fn empty_or_missing_packages_yields_nothing() {
        assert!(run_parser("hex", "", parse_manifest).is_empty());
        assert!(run_parser("hex", "packages = []", parse_manifest).is_empty());
    }

    #[test]
    fn malformed_toml_yields_nothing_without_panicking() {
        assert!(run_parser("hex", "packages = [ { name = ", parse_manifest).is_empty());
    }
}
