//! Haskell Stack (`stack.yaml.lock` -> OSV `Hackage`).
//!
//! `stack.yaml.lock` is autogenerated by Stack next to `stack.yaml`. It pins
//! the fully-resolved `(name, version)` of every extra-dep (and snapshot
//! identity) with sha256+size. We read coordinates ONLY from the `completed:`
//! blocks under the top-level `packages:` list; never `original:`, which may
//! be an unpinned range, bare snapshot ref, or git URL.
//!
//! The `.lock` only pins extra-deps + the snapshot's identity; it does NOT
//! enumerate the hundreds of Stackage snapshot (LTS/Nightly) packages, so this
//! is "extra-deps only" coverage, not the full transitive closure.
//!
//! Hackage names are case-sensitive and may contain hyphens, so the
//! `NAME-VERSION` hackage string is split on the LAST hyphen (the version
//! always begins with a digit). Versions are PVP strings used verbatim.
//!
//! The file is YAML, so neither `serde_json` nor `toml` apply; we hand-roll a
//! tiny line-oriented scanner with no YAML dependency. Detection is the EXACT
//! filename only: a bare `*.lock` glob would hijack Cargo.lock,
//! package-lock.json, poetry.lock, flake.lock, etc.

use super::support::{Emitter, indent_of, unquote};

/// Emit the pinned coordinates from a `stack.yaml.lock`'s `packages:` list.
/// Tolerates malformed input by skipping unparseable records rather than
/// failing; duplicate coordinates are deduped globally per manifest.
pub(super) fn stack_yaml_lock(contents: &str, out: &mut Emitter<'_>) {
    // Any other column-0 key (e.g. `snapshots:`) exits the `packages:`
    // sequence; snapshots carry no coordinates.
    let mut in_packages = false;
    // Buffered (line_no, raw) lines of the current `- completed:` record.
    let mut record: Vec<(usize, &str)> = Vec::new();

    let flush = |record: &mut Vec<(usize, &str)>, out: &mut Emitter<'_>| {
        if let Some((name, version, line)) = parse_record(record) {
            out.pkg(&name, &version, Some(line));
        }
        record.clear();
    };

    for (idx, raw) in contents.lines().enumerate() {
        let line_no = idx + 1;
        let trimmed = raw.trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let indent = indent_of(raw);

        // Entering a new top-level section ends any in-flight record.
        if indent == 0 && trimmed.ends_with(':') && !trimmed.starts_with('-') {
            flush(&mut record, out);
            in_packages = trimmed == "packages:";
            continue;
        }

        if !in_packages {
            continue;
        }

        // A list item at the packages indent starts a new record. Stack writes
        // `- completed:` (a `-` followed by the first child key on the same
        // line); treat any `- ` at indent 0 as the record boundary.
        if indent == 0 && trimmed.starts_with('-') {
            flush(&mut record, out);
            // Keep the line so a same-line `- completed:` is part of the record.
            record.push((line_no, raw));
            continue;
        }

        if !record.is_empty() {
            record.push((line_no, raw));
        }
    }

    // Flush the final record (file may end inside the packages list).
    flush(&mut record, out);
}

/// Extract `(name, version, line)` from one buffered `- completed:` record.
///
/// Reads ONLY from within the `completed:` sub-block. Shape (A): a
/// `hackage: NAME-VERSION@sha256:...,SIZE` scalar. Shape (B): explicit
/// `name:` + `version:` keys (git/archive/local pantry entries).
fn parse_record(record: &[(usize, &str)]) -> Option<(String, String, usize)> {
    let mut completed_child_indent: Option<usize> = None;
    let mut in_completed = false;

    let mut hackage: Option<(&str, usize)> = None;
    let mut name: Option<&str> = None;
    let mut version: Option<&str> = None;
    let mut name_version_line: Option<usize> = None;

    for (line_no, raw) in record {
        let trimmed = raw.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let indent = indent_of(raw);
        // Normalise a possible leading `- ` (the `- completed:` first line).
        let key_part = trimmed.trim_start_matches('-').trim_start();

        if key_part == "completed:" {
            in_completed = true;
            // Children of completed: are more indented than this key.
            // For `- completed:` at indent 0, children sit at indent >= 2.
            completed_child_indent = None; // set on first child below
            continue;
        }

        // An `original:` block (or any sibling of `completed:`) ends the
        // completed sub-block. Such siblings sit at the indent of the key
        // following `- ` (typically 2 for a `- completed:` item).
        if in_completed {
            if let Some(child_indent) = completed_child_indent {
                if indent < child_indent {
                    // Dedented out of completed's children (e.g. `original:`).
                    in_completed = false;
                    continue;
                }
            } else {
                // First child line establishes completed's child indent.
                completed_child_indent = Some(indent);
            }
        }

        if !in_completed {
            continue;
        }

        // Within completed's children, look at the LEAST-indented keys only so
        // we ignore deeper nesting like `pantry-tree:`'s sha256/size.
        if let Some(child_indent) = completed_child_indent
            && indent != child_indent
        {
            continue;
        }

        if let Some(val) = key_part.strip_prefix("hackage:") {
            let v = unquote(val.trim());
            if !v.is_empty() {
                hackage = Some((v, *line_no));
            }
        } else if let Some(val) = key_part.strip_prefix("name:") {
            let v = unquote(val.trim());
            if !v.is_empty() {
                name = Some(v);
                name_version_line.get_or_insert(*line_no);
            }
        } else if let Some(val) = key_part.strip_prefix("version:") {
            let v = unquote(val.trim());
            if !v.is_empty() {
                version = Some(v);
                name_version_line.get_or_insert(*line_no);
            }
        }
    }

    // Shape (A) takes precedence: the hackage scalar is the common case.
    if let Some((coord, line)) = hackage
        && let Some((n, v)) = split_hackage(coord)
    {
        return Some((n, v, line));
    }
    // Shape (B): explicit name + version keys.
    if let (Some(n), Some(v), Some(line)) = (name, version, name_version_line) {
        return Some((n.to_string(), v.to_string(), line));
    }
    None
}

/// Split a hackage coordinate `NAME-VERSION@sha256:HEX,SIZE` into `(name,
/// version)`. Strips everything from the first `@`, then splits `NAME-VERSION`
/// on the LAST hyphen whose following char is a digit (Hackage names contain
/// hyphens; PVP versions always start with a digit).
fn split_hackage(coord: &str) -> Option<(String, String)> {
    // Drop the `@sha256:...,SIZE` suffix (older partial freezes may lack it).
    let name_version = coord.split('@').next().unwrap_or(coord).trim();
    if name_version.is_empty() {
        return None;
    }

    let bytes = name_version.as_bytes();
    let mut split_at: Option<usize> = None;
    for (i, &b) in bytes.iter().enumerate() {
        if b == b'-'
            && let Some(&next) = bytes.get(i + 1)
            && next.is_ascii_digit()
        {
            split_at = Some(i);
        }
    }

    let idx = split_at?;
    let name = &name_version[..idx];
    let version = &name_version[idx + 1..];
    if name.is_empty() || version.is_empty() {
        return None;
    }
    Some((name.to_string(), version.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scan::targets::support::run_parser;

    #[test]
    fn splits_hackage_with_hyphenated_name() {
        // Name contains a hyphen: must split on the LAST hyphen before a digit.
        let (n, v) =
            split_hackage("acme-missiles-0.3@sha256:2ba66a092a32593880a87fb00f3213762,613")
                .unwrap();
        assert_eq!(n, "acme-missiles");
        assert_eq!(v, "0.3");
    }

    #[test]
    fn splits_hackage_without_hash() {
        let (n, v) = split_hackage("aeson-2.1.0.0").unwrap();
        assert_eq!(n, "aeson");
        assert_eq!(v, "2.1.0.0");
    }

    #[test]
    fn parses_lock_completed_only() {
        let input = "\
# This file was autogenerated by Stack.
packages:
- completed:
    hackage: acme-missiles-0.3@sha256:2ba66a092a32593880a87fb00f3213762d7bca65a687d45965778deb8694c5d1,613
    pantry-tree:
      sha256: 614bc0cca76937507ea0a5ccc17a504c997ce458d7f2f9e43b15a10c8eaeb033
      size: 226
  original:
    hackage: acme-missiles-0.3
- completed:
    hackage: optparse-applicative-0.18.1.0@sha256:0e2bdf1d6f2c1a2f,2048
  original:
    hackage: optparse-applicative-0.18.1.0
- completed:
    name: my-forked-lib
    version: 1.4.2
    git: https://github.com/example/my-forked-lib.git
  original:
    git: https://github.com/example/my-forked-lib.git
snapshots:
- completed:
    sha256: 3c412a7c13dba6d3d808455a458e0776c58b6cf99b8a7961a2f5e55589d6f1d6
    size: 729011
    url: https://example.com/lts.yaml
  original: lts-24.43
";
        let got = run_parser("hackage", input, stack_yaml_lock);
        let coords: Vec<(String, String)> = got
            .iter()
            .map(|p| (p.name.clone(), p.version.clone()))
            .collect();
        assert!(coords.contains(&("acme-missiles".to_string(), "0.3".to_string())));
        assert!(coords.contains(&("optparse-applicative".to_string(), "0.18.1.0".to_string())));
        assert!(coords.contains(&("my-forked-lib".to_string(), "1.4.2".to_string())));
        // The snapshot URL/sha256 must NOT produce a coordinate.
        assert_eq!(coords.len(), 3);
    }
}
